version: '3.8'

services:
  vault:
    image: vault
    volumes:
      - ./example:/tmp/example
      - ./logs/:/tmp/logs
    cap_add:
      - IPC_LOCK
    command: server -config /tmp/example/config.hcl
    ports:
      - "8200:8200"
#    depends_on:
#      - postgres
#
#  postgres:
#    image: postgres
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: test
