version: '2'
services:
  vault:
    container_name: vault
    image: vault:1.13.3
    volumes:
      - $PWD/example:/tmp/example
      - $PWD/logs/:/tmp/logs
    cap_add:
      - IPC_LOCK
    command: server -config /tmp/example/config.hcl
    ports:
      - "8200:8200"
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
