name: Lint And Test
env:
  DEV_NODE_VERSION: 18
  # This is the codecov token used to push coverage reports to codecov
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  unit_tests:
    name: Unit tests
    needs: verify_lint
    strategy:
      matrix:
        # We verify compatibility for current and previous LTS
        node_version: [16, 18]
    env:
      NODE_VERSION: ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      # Run unit tests
      - name: Unit tests
        run: npm run test:unit

  verify_lint:
    name: Verify lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Use node 16
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.DEV_NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      # Run lint
      - name: Lint
        run: npm run lint

  inetgration_tests_and_codecov:
    name: Run tests and push to codecov
    runs-on: ubuntu-latest
    needs: verify_lint
    strategy:
      matrix:
        # We verify compatibility for current and previous LTS
        node_version: [16, 18]
    env:
      NODE_VERSION: ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Build testing container
        run: docker build -t tests:${{ github.sha }} --build-arg SET_NODE_VERSION=$NODE_VERSION .
      - name: Invoke testing container
        run: docker run --network container:vault
          -e VAULT_ADDR=http://vault:8200
          -v $PWD/coverage:/app/coverage tests:${{ github.sha }} "cd /app && npm run coverage"
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ env.CODECOV_TOKEN }}
          env_vars: NODE_VERSION # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
