name: Publish NPM and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions:
      id-token: write
      contents: write

    name: Publish release ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Publish
        run: npm publish

      - name: Set version as env var
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5
        name: Release
        with:
          name: Release ${{ env.VERSION }}
