name: Extract & write features
on:
  pull_request:
    branches:
      - master
    paths:
      - "src/commands/**"
jobs:
  main:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract features
        shell: bash
        run: node ./scripts/write-features.js
      - uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # tag: v9.1.3
        with:
          default_author: github_actions
          add: "features.md"
          push: origin HEAD:${{ github.head_ref }} --force-with-lease
          commit: --signoff
